### PR TITLE
Call is_bypassable_request before checking for a directly passed token

### PR DESCRIPTION
**Pull request by Mark90**

### CODE REVIEW

**Comment by torkashvand** [comment]
In a typical scenario where OAUTH2 is active, authentication is mandatory for all requests. Although we have an is_bypassable_request method, it was specifically designed for callback steps that handle their own authentication. Practically, there is no real-world use case for bypassing authentication entirely. This is why the bypass check is placed as the last condition. Essentially, a token must be provided either in the request body or as a URL parameter; there are no scenarios where a request would be allowed without a token.

Otherwise, we shouldn't guard our API with OIDC, as this would imply that the API should be public, such as in the case of a health check endpoint.

**Comment by torkashvand** [comment]
So I believe we can close this PR and as today we saw we prevented a miss use of our protected API. I mean Anna's use case!

what do you think?

**Comment by torkashvand** [comment]
For clarity, we can rename `is_bypassable_request` to something more explicit like `is_bypassable_protected_request`. This makes its purpose and usage clearer.

but I have no strong opinion about it

**Comment by Mark90** [comment]
> In a typical scenario where OAUTH2 is active, authentication is mandatory for all requests with oidc dependency. Although we have an `is_bypassable_request` method, it was specifically designed for callback steps that handle their own authentication. Practically, there is no real-world use case for bypassing authentication entirely. This is why the bypass check is placed as the last condition. Essentially, a token must be provided either in the request body or as a URL parameter; there are no scenarios where a request would be allowed without a token.
> 
> Otherwise, we shouldn't guard our API with OIDC, as this would imply that the API should be public, such as in the case of a health check endpoint.

Hmm, I thought the purpose of bypassing was for users to selectively disable auth on endpoints in the orchestror-core library without disabling Auth entirely.

Either way, the code in `authenticate()` is currently

```python
            if token is None:
                    extracted_id_token = await self.id_token_extractor.extract(request)
                    if not extracted_id_token:
                        return None
                    token_or_extracted_id_token = extracted_id_token
                elif await self.is_bypassable_request(request):
                    return None
                else:
                    token_or_extracted_id_token = token

            user_info: OIDCUserModel = await self.userinfo(async_client, token_or_extracted_id_token)
```

Which means there are 2 possible flows;
1. `token` is passed directly to `authenticate()` -> `is_bypassable_request` is called and if True break out of `authenticate()` without validating the token
2. `token` is not passed directly to `authenticate()` but it's extracted from the request headers -> `is_bypassable_request` is not called at all

Given the above:
* Flow 1 is not relevant in this context as only `authenticate_websocket()` passes a token directly. And in case of a Websocket request, it follows a different code path in `authenticate()`
* Flow 2 means that the bypass is not used

Flow 1 could still apply to requests that are within control of the user, but in that case you could just as well remove the `Depends(authenticate)` on the fastapi route?

Perhaps I'm still overlooking something..

**Comment by torkashvand** [comment]
Mark, I think the name `is_bypassable_request` isn't quite fitting since our intention is to delegate authentication to the API itself, as we did with the callback step. The issue arises because the `token` parameter name conflicts with the `token` parameter in the `callback step`. A more suitable name might be `is_self_authenticated_request`, as it better conveys the purpose of delegating authentication to specific endpoints.

**Comment by torkashvand** [comment]
so I would say I am happy with your changes but I think the `is_self_authenticated_request` is a better name.

**Comment by Mark90** [comment]
Ok, well the problem from Anna is resolved in another way, so there's no need to merge this

**Comment by torkashvand** [comment]
Hi Mark
How are you doing?
Yesterday after debugging the code with [@annaw]
I noticed that there is a bug in my code in oaut2_lib.
In the old code, the token clashed with the callback API token URL path parameter and header token. This was refactored in the new code, and the authenticate method was updated to:
`async def authenticate(self, request: HTTPConnection, token: Optional[str] = None) -> Optional[OIDCUserModel]:`
However, due to this change, the is_bypassable_request method is no longer called for the callback API.
so I wrote a code to fix this and I found you already have a closed PR and it is exactly a fix for this issue as well.

could you open this PR again?

**Review by torkashvand — APPROVED** [review]

**Pull request merged**
